INSERT INTO guest(first_name, last_name, member_since)
VALUES('Aleksander', 'Ivanov', '2022-05-15')
INSERT INTO guest(first_name, last_name, member_since)
VALUES('Ekaterina', 'Smirnova', '2023-01-10')
INSERT INTO guest(first_name, last_name, member_since)
VALUES('Dmitry', 'Petrov', '2021-11-25')
INSERT INTO guest(first_name, last_name, member_since)
VALUES('Olga', 'Kozlova', '2023-04-02')
INSERT INTO guest(first_name, last_name, member_since)
VALUES('Ivan', 'Morozov', '2022-09-18')

INSERT INTO room_type(description_,max_capacity)
VALUES('Standart', 1)
INSERT INTO room_type(description_,max_capacity)
VALUES('Lux', 2)

INSERT INTO reservation(date_in,date_out,made_by,guestID)
VALUES('2023-09-10','2023-09-15','Petrov',3)
INSERT INTO reservation(date_in,date_out,made_by,guestID)
VALUES('2023-08-25','2023-08-28','Smirnova',2)
INSERT INTO reservation(date_in,date_out,made_by,guestID)
VALUES('2023-10-02','2023-10-10','Ivanov', 1)
INSERT INTO reservation(date_in,date_out,made_by,guestID)
VALUES('2023-09-01','2023-09-05','Morozov', 5)
INSERT INTO reservation(date_in,date_out,made_by,guestID)
VALUES('2023-08-20','2023-08-24','Kozlova', 4)

INSERT INTO reserved_room(number_of_rooms,roomTypeID,reservationID,status)
VALUES(2,1,1,'Broneeritud')
INSERT INTO reserved_room(number_of_rooms,roomTypeID,reservationID,status)
VALUES(1,2,2,'Broneeritud')
INSERT INTO reserved_room(number_of_rooms,roomTypeID,reservationID,status)
VALUES(1,1,3,'Broneeritud')
INSERT INTO reserved_room(number_of_rooms,roomTypeID,reservationID,status)
VALUES(1,2,4,'Broneeritud')
INSERT INTO reserved_room(number_of_rooms,roomTypeID,reservationID,status)
VALUES(2,1,5,'Broneeritud')

INSERT INTO room(number,name,status,smoke,roomTypeID)
VALUES(101,'Üheinimese','Vaba',0,1)
INSERT INTO room(number,name,status,smoke,roomTypeID)
VALUES(102,'Pere tuba','Vaba',1,1)
INSERT INTO room(number,name,status,smoke,roomTypeID)
VALUES(206,'Luksus tuba','Hõivatud',0,2)
INSERT INTO room(number,name,status,smoke,roomTypeID)
VALUES(208,'Üheinimese','Hõivatud',0,2)
INSERT INTO room(number,name,status,smoke,roomTypeID)
VALUES(105,'Üheinimese','Hõivatud',0,1)

INSERT INTO occupied_room(check_in,check_out,roomID,reservationID)
VALUES('2023-09-10 14:00', '2023-09-15 23:14',1,1)
INSERT INTO occupied_room(check_in,check_out,roomID,reservationID)
VALUES('2022-04-25 16:51', '2022-05-02 14:05',2,2)
INSERT INTO occupied_room(check_in,check_out,roomID,reservationID)
VALUES('2022-09-23 13:51', '2022-09-27 23:14',3,3)
INSERT INTO occupied_room(check_in,check_out,roomID,reservationID)
VALUES('2023-09-10 14:00', '2023-09-15 14:05',4,4)
INSERT INTO occupied_room(check_in,check_out,roomID,reservationID)
VALUES('2023-09-10 14:00', '2023-09-15 23:14',5,5)

INSERT INTO hosted_at(guestID,occupied_roomID)
VALUES(1,5)
INSERT INTO hosted_at(guestID,occupied_roomID)
VALUES(4,1)
INSERT INTO hosted_at(guestID,occupied_roomID)
VALUES(3,3)
INSERT INTO hosted_at(guestID,occupied_roomID)
VALUES(2,4)
INSERT INTO hosted_at(guestID,occupied_roomID)
VALUES(5,2)